### ISSUE TITLE
Join efforts in ImageInpainting?

### ISSUE THREAD

**Issue by juliohm** [briochemc/Inpaintings.jl#6]
Hi @briochemc ,

Nice work. What do you think of joining efforts in [ImageInpainting.jl](https://github.com/JuliaImages/ImageInpainting.jl)

We have plans to not only in-paint arrays of floats, but also color types. It would be great to have you there working together on new methods.

Best,
-Julio

**Comment by briochemc** [comment]
Hi,

Yes although I am not sure I can help :) I just ported some MATLAB code to Julia ! What did you have in mind? (Note I will be pretty much inactive until January 5th-ish)

Cheers
Benoit

**Comment by juliohm** [comment]
I will be offline until January as well, no worries :)

If you can port these methods to ImageInpainting.jl, that would already be a nice contribution :+1:

That way we can work together on making it Julian style.

Cheers,

**Comment by juliohm** [comment]
I will close the issue since you are already aware of the duplication.
