### ISSUE TITLE
Stencil-Type

### ISSUE THREAD

**Issue by KonradScheffler** [briochemc/Inpaintings.jl#8]
Hey,

I can not really follow which kind of stencil the code is producing for the laplacian. Could you elaborate a bit on this matter? It seems to stick to the horizontal neighbors, but is not producing a classical 5-point stencil in 2D/ 7-point stencil in 3D?

Best,
Konrad

**Comment by briochemc** [comment]
From memory I think it just adds a `[1, -2, 1]` in each dimension, so a central `-4` in 2D, a `-6` in 3D, and so on.

**Comment by briochemc** [comment]
Do you have a MWE where it does *not* produce the classical stencil?

**Comment by KonradScheffler** [comment]
Yeah, the general structure looks like this, but when i build a classical 2D-5 point stencil by using the kronecker sum [(klick)](https://en.wikipedia.org/wiki/Kronecker_sum_of_discrete_Laplacians) my laplacian with hom. dirichlet b.c. looks slightly different in the outer regions:

A=ones(3,3)
n1,n1=size(A)
S = spdiagm(n1,n1,-1=>ones(n1-1),0=>-2*ones(n1),1=>ones(n1-1))
P = spdiagm(n2,n2,-1=>ones(n2-1),0=>-2*ones(n2),1=>ones(n2-1))
Δ = kron(S,I(n1)) + kron(I(n2),P)

produces

![grafik](https://user-images.githubusercontent.com/83588313/143582229-2defeeaa-f8bb-41d4-bf62-4386e569103c.png)

but your code produces:

![grafik](https://user-images.githubusercontent.com/83588313/143582503-b130bf04-534c-4b8d-9300-ff3460bfc2cc.png)

Is the difference due to other boundary conditions?

**Comment by briochemc** [comment]
Yes I think so!

**Comment by briochemc** [comment]
I'll close this but feel free to reopen if you think I did not answer your question!
